//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Countries", Namespace="http://schemas.datacontract.org/2004/07/FlightProvider")]
    public partial class Countries : object
    {
        
        private int CountryIdField;
        
        private string CountryNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId
        {
            get
            {
                return this.CountryIdField;
            }
            set
            {
                this.CountryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName
        {
            get
            {
                return this.CountryNameField;
            }
            set
            {
                this.CountryNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cities", Namespace="http://schemas.datacontract.org/2004/07/FlightProvider")]
    public partial class Cities : object
    {
        
        private int CityIdField;
        
        private string CityNameField;
        
        private int CountryIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityId
        {
            get
            {
                return this.CityIdField;
            }
            set
            {
                this.CityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName
        {
            get
            {
                return this.CityNameField;
            }
            set
            {
                this.CityNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId
        {
            get
            {
                return this.CountryIdField;
            }
            set
            {
                this.CountryIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchRequest", Namespace="http://schemas.datacontract.org/2004/07/FlightProvider")]
    public partial class SearchRequest : object
    {
        
        private System.DateTime ArrivalDateField;
        
        private System.DateTime DepartureDateField;
        
        private int DestinationCityIdField;
        
        private int DestinationCountryIdField;
        
        private int OriginCityIdField;
        
        private int OriginCountryIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ArrivalDate
        {
            get
            {
                return this.ArrivalDateField;
            }
            set
            {
                this.ArrivalDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DepartureDate
        {
            get
            {
                return this.DepartureDateField;
            }
            set
            {
                this.DepartureDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DestinationCityId
        {
            get
            {
                return this.DestinationCityIdField;
            }
            set
            {
                this.DestinationCityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DestinationCountryId
        {
            get
            {
                return this.DestinationCountryIdField;
            }
            set
            {
                this.DestinationCountryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OriginCityId
        {
            get
            {
                return this.OriginCityIdField;
            }
            set
            {
                this.OriginCityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OriginCountryId
        {
            get
            {
                return this.OriginCountryIdField;
            }
            set
            {
                this.OriginCountryIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlightData", Namespace="http://schemas.datacontract.org/2004/07/FlightProvider")]
    public partial class FlightData : object
    {
        
        private ServiceReference1.FlightOption FlightOptionField;
        
        private ServiceReference1.PlaneRoute PlaneRouteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.FlightOption FlightOption
        {
            get
            {
                return this.FlightOptionField;
            }
            set
            {
                this.FlightOptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.PlaneRoute PlaneRoute
        {
            get
            {
                return this.PlaneRouteField;
            }
            set
            {
                this.PlaneRouteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlightOption", Namespace="http://schemas.datacontract.org/2004/07/FlightProvider")]
    public partial class FlightOption : object
    {
        
        private string DestinationAirportField;
        
        private string FlightNumberField;
        
        private string OriginAirportField;
        
        private decimal PriceField;
        
        private string RouteNumberField;
        
        private string SeatNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationAirport
        {
            get
            {
                return this.DestinationAirportField;
            }
            set
            {
                this.DestinationAirportField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlightNumber
        {
            get
            {
                return this.FlightNumberField;
            }
            set
            {
                this.FlightNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginAirport
        {
            get
            {
                return this.OriginAirportField;
            }
            set
            {
                this.OriginAirportField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RouteNumber
        {
            get
            {
                return this.RouteNumberField;
            }
            set
            {
                this.RouteNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeatNumber
        {
            get
            {
                return this.SeatNumberField;
            }
            set
            {
                this.SeatNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlaneRoute", Namespace="http://schemas.datacontract.org/2004/07/FlightProvider")]
    public partial class PlaneRoute : object
    {
        
        private System.DateTime ArrivalDateTimeField;
        
        private System.DateTime DepartureDateTimeField;
        
        private int DestinationCountryIdField;
        
        private int DestionationCityIdField;
        
        private int OriginCityIdField;
        
        private int OriginCountryIdField;
        
        private string RouteNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ArrivalDateTime
        {
            get
            {
                return this.ArrivalDateTimeField;
            }
            set
            {
                this.ArrivalDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DepartureDateTime
        {
            get
            {
                return this.DepartureDateTimeField;
            }
            set
            {
                this.DepartureDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DestinationCountryId
        {
            get
            {
                return this.DestinationCountryIdField;
            }
            set
            {
                this.DestinationCountryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DestionationCityId
        {
            get
            {
                return this.DestionationCityIdField;
            }
            set
            {
                this.DestionationCityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OriginCityId
        {
            get
            {
                return this.OriginCityIdField;
            }
            set
            {
                this.OriginCityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OriginCountryId
        {
            get
            {
                return this.OriginCountryIdField;
            }
            set
            {
                this.OriginCountryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RouteNumber
        {
            get
            {
                return this.RouteNumberField;
            }
            set
            {
                this.RouteNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTicketResponseModel", Namespace="http://schemas.datacontract.org/2004/07/FlightProvider.Model")]
    public partial class GetTicketResponseModel : object
    {
        
        private System.DateTime DepartureDateField;
        
        private string DestinationAirportField;
        
        private string DestinationCityField;
        
        private string DestinationCountryField;
        
        private System.DateTime DestinationDateField;
        
        private string FlightNumberField;
        
        private string OriginAirportField;
        
        private string OriginCityField;
        
        private string OriginCountryField;
        
        private decimal PriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DepartureDate
        {
            get
            {
                return this.DepartureDateField;
            }
            set
            {
                this.DepartureDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationAirport
        {
            get
            {
                return this.DestinationAirportField;
            }
            set
            {
                this.DestinationAirportField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationCity
        {
            get
            {
                return this.DestinationCityField;
            }
            set
            {
                this.DestinationCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationCountry
        {
            get
            {
                return this.DestinationCountryField;
            }
            set
            {
                this.DestinationCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DestinationDate
        {
            get
            {
                return this.DestinationDateField;
            }
            set
            {
                this.DestinationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlightNumber
        {
            get
            {
                return this.FlightNumberField;
            }
            set
            {
                this.FlightNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginAirport
        {
            get
            {
                return this.OriginAirportField;
            }
            set
            {
                this.OriginAirportField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginCity
        {
            get
            {
                return this.OriginCityField;
            }
            set
            {
                this.OriginCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginCountry
        {
            get
            {
                return this.OriginCountryField;
            }
            set
            {
                this.OriginCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAirProvider")]
    public interface IAirProvider
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirProvider/GetCountries", ReplyAction="http://tempuri.org/IAirProvider/GetCountriesResponse")]
        ServiceReference1.Countries[] GetCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirProvider/GetCountries", ReplyAction="http://tempuri.org/IAirProvider/GetCountriesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Countries[]> GetCountriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirProvider/GetCities", ReplyAction="http://tempuri.org/IAirProvider/GetCitiesResponse")]
        ServiceReference1.Cities[] GetCities(int countryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirProvider/GetCities", ReplyAction="http://tempuri.org/IAirProvider/GetCitiesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Cities[]> GetCitiesAsync(int countryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirProvider/GetCountryById", ReplyAction="http://tempuri.org/IAirProvider/GetCountryByIdResponse")]
        string GetCountryById(int countryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirProvider/GetCountryById", ReplyAction="http://tempuri.org/IAirProvider/GetCountryByIdResponse")]
        System.Threading.Tasks.Task<string> GetCountryByIdAsync(int countryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirProvider/GetCityById", ReplyAction="http://tempuri.org/IAirProvider/GetCityByIdResponse")]
        string GetCityById(int cityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirProvider/GetCityById", ReplyAction="http://tempuri.org/IAirProvider/GetCityByIdResponse")]
        System.Threading.Tasks.Task<string> GetCityByIdAsync(int cityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirProvider/AvailabilitySearch", ReplyAction="http://tempuri.org/IAirProvider/AvailabilitySearchResponse")]
        ServiceReference1.FlightData[] AvailabilitySearch(ServiceReference1.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirProvider/AvailabilitySearch", ReplyAction="http://tempuri.org/IAirProvider/AvailabilitySearchResponse")]
        System.Threading.Tasks.Task<ServiceReference1.FlightData[]> AvailabilitySearchAsync(ServiceReference1.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirProvider/GetTicket", ReplyAction="http://tempuri.org/IAirProvider/GetTicketResponse")]
        ServiceReference1.GetTicketResponseModel GetTicket(string flightNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirProvider/GetTicket", ReplyAction="http://tempuri.org/IAirProvider/GetTicketResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetTicketResponseModel> GetTicketAsync(string flightNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IAirProviderChannel : ServiceReference1.IAirProvider, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class AirProviderClient : System.ServiceModel.ClientBase<ServiceReference1.IAirProvider>, ServiceReference1.IAirProvider
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AirProviderClient() : 
                base(AirProviderClient.GetDefaultBinding(), AirProviderClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAirProvider.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AirProviderClient(EndpointConfiguration endpointConfiguration) : 
                base(AirProviderClient.GetBindingForEndpoint(endpointConfiguration), AirProviderClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AirProviderClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AirProviderClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AirProviderClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AirProviderClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AirProviderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference1.Countries[] GetCountries()
        {
            return base.Channel.GetCountries();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Countries[]> GetCountriesAsync()
        {
            return base.Channel.GetCountriesAsync();
        }
        
        public ServiceReference1.Cities[] GetCities(int countryId)
        {
            return base.Channel.GetCities(countryId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Cities[]> GetCitiesAsync(int countryId)
        {
            return base.Channel.GetCitiesAsync(countryId);
        }
        
        public string GetCountryById(int countryId)
        {
            return base.Channel.GetCountryById(countryId);
        }
        
        public System.Threading.Tasks.Task<string> GetCountryByIdAsync(int countryId)
        {
            return base.Channel.GetCountryByIdAsync(countryId);
        }
        
        public string GetCityById(int cityId)
        {
            return base.Channel.GetCityById(cityId);
        }
        
        public System.Threading.Tasks.Task<string> GetCityByIdAsync(int cityId)
        {
            return base.Channel.GetCityByIdAsync(cityId);
        }
        
        public ServiceReference1.FlightData[] AvailabilitySearch(ServiceReference1.SearchRequest request)
        {
            return base.Channel.AvailabilitySearch(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.FlightData[]> AvailabilitySearchAsync(ServiceReference1.SearchRequest request)
        {
            return base.Channel.AvailabilitySearchAsync(request);
        }
        
        public ServiceReference1.GetTicketResponseModel GetTicket(string flightNumber)
        {
            return base.Channel.GetTicket(flightNumber);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetTicketResponseModel> GetTicketAsync(string flightNumber)
        {
            return base.Channel.GetTicketAsync(flightNumber);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAirProvider))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAirProvider))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:5001/AirProviderService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AirProviderClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAirProvider);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AirProviderClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAirProvider);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAirProvider,
        }
    }
}
